project:
  type: website
  output-dir: docs

website:
  title: "Kelsey McGuire"
  favicon: images/mountain-kelsey.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - past-research.qmd
      - href: files/Mcguire_CV_Jun18.pdf
        text: CV

format:
  html:
    theme:
      light: sandstone
      dark: darkly
    css: styles.css
    toc: true

editor: visual

